In [32]:
!conda env list

zsh:1: command not found: conda

In [33]:
from tt_gutenberg.data import load_data

In [41]:
import pandas as pd

In [34]:
authors = load_data('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-06-03/gutenberg_authors.csv')

In [35]:
authors["alias"].value_counts().head(20)

alias
Jarvis, E. K.                          3
Holmes, Gordon                         2
Willis, R. (Robert)                    2
U.S.A.                                 1
Dodgson, Charles Lutwidge              1
Melville, Hermann                      1
Smith, Joseph                          1
United States President (1809-1817)    1
Jay, J. (John)                         1
Longfellow, Henry W.                   1
Townsend, George Tyler                 1
Wells, Herbert George                  1
Crayon, Geoffrey                       1
Stevenson, R. L. (Robert Louis)        1
Descartes, Rene                        1
Engels, Frederick                      1
Thoreau, Henry D. (Henry David)        1
Smith, Johnston                        1
Presno, Odd de                         1
Hawkins, Anthony Hope                  1
Name: count, dtype: int64

In [36]:
metadata = load_data('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-06-03/gutenberg_metadata.csv')

In [37]:
metadata.head()

   gutenberg_id  ... has_text
0             1  ...     True
1             2  ...     True
2             3  ...     True
3             4  ...     True
4             5  ...     True

[5 rows x 8 columns]

In [38]:
languages = load_data('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-06-03/gutenberg_languages.csv')

In [39]:
languages.head()

   gutenberg_id language  total_languages
0             1       en                1
1             2       en                1
2             3       en                1
3             4       en                1
4             5       en                1

In [43]:
author_works = pd.merge(authors, metadata, on="gutenberg_author_id")

In [55]:
#author_works.head()
author_works.shape
#authors.shape

(76694, 14)

In [52]:
author_languages = pd.merge(author_works, languages, on="gutenberg_id")

In [54]:
# author_languages.head()
author_languages.shape

(76901, 16)

In [56]:
author_languages.columns

Index(['gutenberg_author_id', 'author_x', 'alias', 'birthdate', 'deathdate',
       'wikipedia', 'aliases', 'gutenberg_id', 'title', 'author_y',
       'language_x', 'gutenberg_bookshelf', 'rights', 'has_text', 'language_y',
       'total_languages'],
      dtype='str')

In [65]:
(
    author_languages
    .groupby("alias")["language_y"]
    .nunique()
    .sort_values(ascending=False)
    .index
    .tolist()

)

['Grimm, Jacob Ludwig Carl',
 'Grimm, Wilhelm Carl',
 'Andersen, Hans Christian',
 "Wilde, Oscar Fingal O'Flahertie Wills",
 'Stevenson, R. L. (Robert Louis)',
 'Alighieri, Dante',
 'Όμηρος',
 'Poe, Edgar Allen',
 'Πλάτων',
 'Swift, J. (Jonathan)',
 'De Maupassant, Guy',
 'Chaney, John Griffith',
 'Dodgson, Charles Lutwidge',
 'Von Schmid, Christoph',
 'Wells, Herbert George',
 'Rollan, R.',
 'Darwin, Charles Robert',
 'Crayon, Geoffrey',
 'Descartes, Rene',
 'Gloux, Olivier',
 'Mill, J. S. (John Stuart)',
 'Harte, Francis Bret',
 'Wallace, Lewis',
 'Heine, H. (Heinrich)',
 'Curwood, James-Oliver',
 'Ohnet, Jorge',
 'Branch, Stephen',
 'Malot, Hector-Henri',
 'Bunyan, Johann',
 'Whitman, Walter',
 'Buonarroti, Michelangelo',
 'Michelet, J.',
 'Racine, Jean Baptiste',
 'Reuter, Heinrich Ludwig Christian Friedrich',
 'Ruskin, J. (John)',
 'Strindberg, Johan August',
 'Merimee, Prosper',
 'Engels, Frederick',
 'Chaucer, Jeffrey',
 'Augustine, Saint',
 '孔子',
 'Murger, Henry',
 'Daudet, Louis Marie Alphonse',
 'Erasmus, of Rotterdam',
 'Tennyson, Alfred Lord',
 'Storm, Hans Theodor Woldsen',
 'Diderot, Pantophile',
 'Weyman, Stanley J. (Stanley John)',
 'Maranan, Apolinario Mabini y',
 'Verlaine, Paul Marie',
 'Warneford, Lieutenant',
 'Donquichote, Marguerite',
 'Hawkins, Anthony Hope',
 'Hauptmann, Gerhart Johann Robert',
 'Longfellow, Henry W.',
 'Shelley, P. B. (Percy Bysshe)',
 'Carlyle, T. (Thomas)',
 'Collins, William Wilkie',
 'Keller, Gotfryd',
 'Key, Ellen Karolina Sofia',
 'Válmíki',
 'Brehm, A. E. (Alfred Edmund)',
 'Goldsmit, Oliver',
 'Wassermann, Jacob',
 'Freitag, Gustav',
 'Bazin, Rene',
 'Long, William Joseph',
 'Campe, J. H. (Joachim Heinrich)',
 'Stevenson, Burton E.',
 'Steiner, Rudolph',
 'Zschokke, Johann Heinrich Daniel',
 'Barnivelt, Esdras',
 'Peltonen, Vihtori',
 'Haeckel, Ernst Heinrich Philipp August',
 'Couperus, Louis Marie Anne',
 'Bush, W. (Wilhelm)',
 'Sardou, V. (Victorien)',
 'Sallustius Crispus, Gaius',
 'Nodier, Jean Charles Emmanuel',
 'Kock, Charles Paul de',
 'Dekker, Eduard Douwes',
 'Brown, Giorgio Rossi',
 'Lessing, G. E.',
 'Boethius, Anicius Manlius Severinus',
 'Ewald, Karl',
 'Jacobsen, Jens Peter',
 'Verhaeren, Émile',
 'Michaelis, Richard C.',
 'Charles, Elisabeth Rundle',
 'Della Porta, Giambattista',
 'Yorick, Mr.',
 'Ford, Ricardo',
 'Westermarck, Edvard Alexander',
 'Montalte, Louis de',
 'Ceynowa, Florian Stanislaw',
 'Woolsey, Sarah Chauncey',
 'Junghuhn, F. W.',
 'Bell, Gertrude Margaret Lowthian',
 'Lemercier, Eugene Emmanuel',
 'Plautus, Marcus Accius',
 'Cotterill, Henry Bernard',
 'Gozlan, Leon',
 'Arrhenius, Svante August',
 'Falkner, J. Meade (John Meade)',
 'Davis, Frederick Hadland',
 'Young, Artur',
 'Sayer, Geo. J.',
 'Delepierre, Joseph Octave',
 'Lie, Jonas Lauritz Idemil',
 'Spence, James Lewis Thomas Chalmers',
 'Strachey, Giles Lytton',
 'Hartmann, F. (Franz)',
 'Jones, Alfred Ernest',
 'Hull, Edith Maude',
 'De Fornaro, Carlo',
 'De Gorostiza, Manuel Eduardo',
 'Forster, Edward Morgan',
 'Mitre, Bartolome',
 'Cousin, Vittorio',
 'Planck, Max Karl Ernst Ludwig',
 'Raleigh, Sir Walter Alexander',
 'Huizinga, J. (Johan)',
 'Jones, Raymond F. (Raymond Fisher)',
 'Rakosi, Viktor',
 'De Wit, Augusta',
 'Wyss, J. D. (Johann David)',
 'Moinaux, J. (Jules)',
 'Mitchell, J. A. (John Ames)',
 'Harting, P. (Pieter)',
 'Papini, G. (Giovanni)',
 'Faccio, Rina',
 'Li, Ya-ko',
 'Lermina, Jules Hippolyte',
 'Moisa, Dorin T.',
 'Faraday, M. (Michael)',
 "O'Connor, John Charles",
 'Wells, David A.',
 'Scheepstra, Hendericus',
 'Lemonnier, Antoine Louis Camille',
 'Weule, K. (Karl)',
 'Seume, J. G. (Johann Gottfried)',
 'Boyer, A. (Abel)',
 'Bougainville, comte de (Louis-Antoine)',
 'Finnemore, J. (John)',
 'Gjellerup, Karl Adolph',
 'Churton Braby, Maud',
 'Uzanne, Louis Octave',
 'Hegel, G. W. F. (Georg Wilhelm Friedrich)',
 'Urpia, Jaime Luciano Balmes',
 'Lowell, Edward Jackson',
 'Heer, Jakob Christoph',
 'Urbanus',
 'Sewell, Ana',
 'Figuier, Guillaume-Louis',
 'Veniero, Lorenzo',
 "D'Holbach, Baron",
 'Borrow, George Henry',
 'Bang, Herman Joachim',
 'Iron, Ralph',
 'Fletcher, Joseph Smith',
 'Shackleton, E. H. (Ernest Henry), Sir',
 'Bates, Harriet Leonora Vose',
 'Wilder, Thornton Niven',
 'Vanderem, Fernand',
 'Menant, Dauphine',
 'Ostwald, Friedrich Wilhelm',
 'Crowther, S. (Samuel)',
 'Wilberforce, W. (William)',
 'Seignobos, Ch. (Charles)',
 'Hemon, Louis',
 'Stedman, Jean-Gabriel',
 'Luska, Sidney',
 'Ingelius, A. G.',
 'Hemmer, Jarl Robert',
 'Serner, Gunnar',
 'Huxley, T. H. (Thomas Henry)',
 'Lundegard, Axel',
 'Ingram, Eleanor Marie',
 'Valois, Marguerite de',
 'Banfield, Edmund James',
 'Loránd, Arnold',
 'Lindman, Voldemar',
 'Cherbuliez, Charles Victor',
 'Lock, John',
 'Giacosa, G. (Giuseppe)',
 'Fechner, G. Th. (Gustav Theodor)',
 'Ernst, Otto',
 'Schlemihl, Peter',
 'Tweedsmuir, John Buchan, Baron',
 'Liszt, F. (Franz)',
 'Jensen, Johannes Vilhelm',
 'Bebel, Auguste',
 'Brillat-Savarin, Jean Anthelme',
 'Obama, Barack Hussein, II',
 'Pluschow, Gunther',
 'Linnaeus, Carolus',
 'Stoker, Abraham',
 'Lindsay, T. M. (Thomas Martin)',
 'Goose, Mary Susan',
 'Beck, James Montgomery',
 'Stallman, Richard M.',
 'Ubaldino, Petruccio',
 'Borel, Jean',
 'Chevalier, Michael',
 'Glyn, Elinor Sutherland',
 'Lorenc, Frantisek Vladimir',
 'Jacobs, William Wymark',
 'Jagor, Andreas Fedor',
 'Fewkes, J. Walter (Jesse Walter)',
 'Beach, Rex Ellingwood',
 'Crawford, Francis Marion',
 'Boothby, Guy Newell',
 'Ferri, Enrique',
 'Hayes, Charles Frederic',
 'Lonnrot, Elias',
 'Paine, Walter Lionel',
 'Goffic, Charles Le',
 'Brazil. Commissao, Exposicao internacioncal de borracha de New York, 1912',
 'Polko, E. (Elise)',
 'Schopfer, Jean',
 'Oksanen, A.',
 'Junius',
 'Baruch, Moses',
 'Delpit, Marc-Adrien',
 'Ritchie, F. (Francis)',
 'Marcus Vitruvius Pollio',
 'Morley, Christopher Darlington',
 'Roessler, Erwin William Eugene',
 'Philippe, Ch.-L. (Charles-Louis)',
 'Watson, John',
 'Runa',
 'Disraeli, B. (Benjamin), Earl of Beaconsfield',
 'Lasker, Eduard',
 'Coote, Miss',
 'Runeberg, J. L. (Johan Ludvig)',
 'Nansen, P. (Peter)',
 'Blanc, H. (Henry)',
 'Latzko, Adolf Andreas',
 'Newton, Sir Isaac',
 'Voß, Richard',
 'Sinjohn, John',
 'Greenfield, Gulielmus',
 'Collado, D. (Diego)',
 'Keller, Helen Adams',
 'Drago, Luis Maria',
 'Blanche, August Teodor',
 'Slousch, Nahum',
 'Gubernatis, Angelo de, conte',
 'Fry, Sheila Kaye-Smith',
 'Ellis, Henry Havelock',
 'Soderhjelm, Alma',
 '谷崎潤一郎',
 'Wallace, Richard Horatio Edgar',
 'Bushnell, Curtis Clark',
 'Morne, Arvid',
 'Revesz, Bela',
 'Pfeiffer, Ida Reyer',
 'Kyrburg, Fritz von der',
 'Hobson, John Atkinson',
 'Edwardes, Edward Tickner',
 'Donner, O. (Otto)',
 'Maundeville, John',
 'Burckhardt, Jakob Christoph',
 'Alcock, D.',
 'Hocker, Gustav',
 'Mosso, Angelo',
 'Labaigt, Laurent',
 'Aguinaldo y Famy, Emilio',
 'Edwards, O. M., Sir',
 '曹雪芹',
 'Eden, Charles Henry',
 'Tavaststjerna, Karl A. (Karl August)',
 'Bull, Jakob B.',
 'Birt, Theodorus',
 'Rollin, Carol',
 'Friis, Jens Andreas',
 'Gaboriau, Émile',
 'Smith, Sarah',
 'Pennell, Theodore Leighton',
 'Bernard, Paul',
 'Peard, Frances M. (Frances Mary)',
 'Dodge, M. E. (Mary Elizabeth)',
 'Kroeh, Charles F.',
 'Cameron, V. L. (Verney Lovett)',
 'Carlet, Pierre',
 'Roux, Hugues le',
 'Beyrich, Clementine (Helm), Frau',
 'Busch, Julius Hermann Moritz',
 'Endle, S. (Sidney)',
 'Von Liebig, Justus, Freiherr',
 'Gasson, Herbert N. (Herbert Newton)',
 'Maspero, Gaston Camille Charles, Sir',
 'Enochs, James Bryon',
 'Pegge, S. (Samuel)',
 'Aneurin',
 'Caius Julius Phaedrus',
 'Caspari, Karl Heinrich',
 'Corroyer, Édouard',
 'Wecksell, Josef Julius',
 'Gunnarsons, Gunnars',
 'Δημοσθένης',
 'Wedekind, Benjamin Franklin',
 'Guerrazzi, F. D. (Francesco Domenico)',
 'Cairon, Claude Antoine Jules',
 'Blommaert, Willem',
 'Rebecque, Henri Benjamin Constant de',
 'Guthrie, Thomas Anstey',
 'Murray, M. A. (Margaret Alice)',
 'Kloosterman, Jan Ritskes',
 'Mallanaga',
 'Souvestre, Emile',
 'Tourgee, Albion Winegar',
 'Malatesta, Enrico',
 'Robida, A. (Albert)',
 'Anderson, James Drummond',
 'Norris, Benjamin Franklin',
 'Tegner, Esaias',
 'Topelius, Toini Mathilda',
 'Sabatini, R.',
 'Hackluyt, Richard',
 'Holmes, Gordon',
 'Benoit, Pierre',
 'Гончаров, Иван Александрович',
 'Wangemann, Eduard Carl Otto',
 'Kafka, F. (Franz)',
 'Massenet, J. (Jules)',
 'Huch, Ricarda Octavia',
 'Mainwaring, C. L.',
 'Gurdon, Philip Richard Thornhagh',
 'Pearce, Joseph Henry',
 'Pearce, E. H. (Ernest Harold)',
 'Overstreet, Harry Allen',
 'Pain, Thomas',
 'Overseer',
 'Overton, J. H. (John Henry)',
 'Peck, J. M. (John Mason)',
 'Pain, Barry Eric Odell',
 'Peabody, F. W. (Frederick William)',
 'Peabody, E. P. (Elizabeth Palmer)',
 'Pear, Tom Hatherley',
 'Peck, R. H.',
 'Peano, G. (Giuseppe)',
 'Pailleron, Édouard Jules Henri',
 'Overton, Grant Martin',
 'Peake, Harold John Edward',
 'Pace, Thomas C.',
 'Peck, J. L. (John Lord)',
 'Pearce, William P. (William Peter)',
 'Packard, Robert Lewis',
 'Pearson, Arthur Cyril',
 'Packeny, Elsa Maria',
 'Paavo-Kallio, Esaias',
 'Pearson, Charles Henry',
 'Pearse, H. H. S. (Henry Hiram Steere)',
 'P. B. St.',
 'Ozaki, Yukio, Madame',
 'Pearson, E. L. (Edmund Lester)',
 'Oxley, James M. (James Macdonald)',
 'Paddock, Buckley B.',
 'Pearse, Guy Mark',
 'Owen, Robert Latham',
 'Pears, James R.\u200f',
 'Paden, Clifton',
 'Paes, Domingo',
 'Pearson, Thomas Gilbert',
 'Pease, A. E. (Alfred Edward), Sir',
 'Owen, John, Rector of Paglesham, Essex',
 'Paez, Ramon',
 'Paganino, Rodrigo Botelho da Fonseca',
 'Owen, Jean Allan',
 'Pearn, Violet A.',
 'Page, Gerald Wilburn',
 'Paget, Violet',
 'Peck, Annie Smith',
 'Peck, George Wilbur',
 'Payne-Gallwey, Ralph William Frankland, Sir, bart.',
 'Pallander, Gunnar',
 'Payne, Paul Lawrence',
 'Partridge, George Everett',
 'Paris, J. A. (John Ayrton)',
 'Parrish, George Dillwyn',
 'Paredes, Manuel Rigoberto',
 'Parry, Edwin Francis',
 'Pardee, Richard Gay',
 'Parsons, B. (Benjamin)',
 'Parsons, S. B.',
 'Parsons, Wm. Barclay (William Barclay)',
 'Partridge, Edward Bellamy',
 'Paquiro',
 'Payne, Buckner Harrison',
 'Pascal, Theophile',
 'Paske, Charles Thomas',
 'Passos, John Dos',
 'Patanjali',
 'Panton, Jane Ellen',
 'Patch, Edith Marion',
 'Patchin, Frank Glines',
 'Paternoster, George Sidney,',
 'Panshin, Alexis Adams',
 'Park, J. R. (John Ranicar)',
 'Park, James Alan, Sir',
 'Park, Robert E.',
 'Parker, Amos Andrew',
 'Parkman, F. (Francis)',
 'Parker, Louis N. (Louis Napoleon)',
 'Parker, L. S. (Lester Shepard)',
 'Parkman, Mary R.',
 'Parker, James Gordon',
 'Parley, Peter',
 'Parker, J. H. (John Henry)',
 'Parker, Henry',
 'Parker, George, Earl of Macclesfield',
 'Parliament, British',
 'Parloa, Miss (Maria)',
 'Parmanen, Eino I.',
 'Parker, E. H. (Edward Harper)',
 'Parnel, Thomas',
 'Parquet, Marguerite Du',
 'Parker, Dorothy Rothschild',
 'Parker, DeWitt H. (DeWitt Henry)',
 'Parr, Harriet',
 'Parr, Mrs. (Louisa Taylor)',
 'Patmore, Coventry Kersey Dighton',
 'Patmore, Peter George',
 'Paton, Andrew Archibald',
 'Parker, Richard Barry',
 'Palgrave, Francis T.',
 'Patterson, John Henry',
 'Patteson, Susanna Louise',
 'Palffy, Albert',
 'Paul, Ford',
 'Paul, Herbert Woodfield',
 'Paul, Sir John Dean, bart.',
 'Pauli, Simon',
 'Palacios, Pedro Bonifacio',
 'Pakiser, Louis Charles',
 'Pakh, Albert',
 'Paulton, Edward Antonio',
 'Paxson, Frederic Logan',
 'Paxton, John D.',
 'Paivarinta, Pietari',
 'Pay, Committee on Railway Mail',
 'Painter, Franklin Verzelius Newton',
 'Payen, Jean-François',
 'Paine, Ralph D. (Ralph Delahaye)',
 'Patterson, J. M. (Joseph Medill)',
 'Pallme, Ignatius',
 'Panizza, Oscar',
 'Palmer, Alice Elvira Freeman',
 'Panin, I. (Ivan)',
 'Pangloss, docteur',
 'Palmer, William Thomas',
 'Palmer, W. Scott (William Scott)',
 'Paton, John G.',
 'Palmer, Josephine L.',
 'Patrat, J. (Joseph)',
 'Palmer, John Leslie',
 'Palmer, Herbert Edward',
 'Palmer, H. E. (Harold E.)',
 'Patricio, Antonio',
 'Patricio, Ladislau',
 'Patricola',
 'Pattee, George Kynett',
 'Palmer, E. H. (Edward Henry)',
 'Palmer, Donald Ellsworth',
 'Palmer, Austin Norman',
 'Patterson, Anne Virginia Sharpe',
 'Patterson, Caleb Perry',
 'A Bushman',
 'Ohrwalder, Joseph',
 'Ottolini, Vittore',
 'Newark, N.J. College of Engineering',
 'Nicklin, John Arnold',
 'Nicholson, Joseph Shield',
 'Nicholson, James Bartram',
 'Nicholson, H. Alleyne (Henry Alleyne)',
 'Nichols, W. T.',
 'Nichols, Robert Malise Bowyer',
 'Nichols, James Thomas',
 'Nichols, James M.',
 'Nichols, James Lawrence',
 'Nicaise, Charles-Louis Auguste',
 'Newton, R. Heber (Richard Heber)',
 'Newton, John',
 'Newton, Alexander Herritage',
 'Newte, Horace Wykeham Can',
 'Newsholme, Sir Arthur',
 'Newmann, Louis',
 'Newman, F. W. (Francis William)',
 'Newman, Edward Manuel',
 'Newlin, William Henry',
 'Newlin, Katharine',
 'Newland, Henry Garrett',
 'Newell, Robert Henry',
 'Newell, P. S. (Peter S.)',
 'Newell, M. Moyca',
 'Newell, Geo. E.',
 'Newbigin, Marion Isabel',
 'Newberry, Percy Edward',
 'Nicolas, Lady Sarah Davison',
 'Nicolay, John George',
 'Nicolini, Giovanni Battista',
 'Noah, Mordecai Manuel',
 'Nordlund, K. (Karl)',
 'Nordhoff, Charles Bernard',
 'Nordenskiold, A. E. (Adolf Erik)',
 'Nordberg, Carl Edin',
 'Nonagenarian',
 'Noll, R. C.',
 'Nolan, Edward Henry',
 'Nogent, Guibert de',
 'Noe, Sydney Philip',
 'Noe, James Thomas Cotton',
 'Nobre, Antonio',
 'Noble, Theophilus Charles',
 'Nizam-ud-din-Ahmad',
 'Nieboer, Herman Jeremias',
 'Nixon, Oliver Woodson',
 'Niven, Frederick John',
 'Nitsch, Helen Alice Matthews',
 'Nisbet, James Hume',
 'Nilsson, Martin Persson',
 'Nilsen, Eric',
 'Niewadomska, Cecylia',
 'Niemi, A. R. (Aukusti Robert)',
 'Nielsen, Jens Peter Zakarias',
 'Nielsen, Anton',
 'Niederlein, Gustav',
 'Niebuhrius, B. G. (Barthold Georg)',
 'Newberry, Fanny E. (Fanny Ellsworth)',
 'New York detective',
 'Norman, B. M. (Benjamin Moore)',
 'New York Historical Association',
 'Nasmith, George G. (George Gallie)',
 'Nash, Mrs. William H.',
 'Naquet, A. (Alfred)',
 'Napton, W. B. (William Barclay)',
 'Nankivell, Edward James',
 'Name, Addison Van',
 'Nagy, Ignacz',
 'Myers, Philip Van Ness',
 'Myers, Frederic William Henry',
 'Myddleton, William Henry',
 'Muzzey, Artemas Bowers',
 'Mutzenberg, Chas. G.',
 'Mustakallio, Johannes',
 'Musson, S. C. (Spencer C.)',
 'Mussey, Reuben Dimond',
 'Musgrave, Dr. (Samuel)',
 'Musel, Robert',
 'Muse, Ben',
 'Murrey, Thomas Jefferson',
 'Murray, William Henry Harrison',
 'Murray, Thomas Boyles',
 'Murray, Robert Fuller',
 'Murray, James A. H.',
 'Murray, Henry Anthony',
 'Murray, H. Kincaid',
 'Murray, Elsie Riach',
 'Murray, David Leslie',
 'Nassau, R. H. (Robert Hamill)',
 'Nathan, Annie',
 'Nathorst, Alfred Gabriel',
 'Nepomuk',
 'New York (Colony). Legislative Council',
 'Neville, Kris Ottman',
 'Neville, Emily Cheney',
 'Nevill, Ralph Henry',
 'Neveux, Pol Louis',
 'Neuman, Nancy W. Hawkins',
 'Neufeld, Carl',
 'Netscher, A. D. van der gon',
 'Netherton, Ross D. (Ross De Witt)',
 'Nessmuk',
 'Neralc, Jenny',
 'Nepoty, Lucien',
 'Nelson, W. S.',
 'National Live Stock & Meat Board',
 'Nelson, Hector William',
 'Nelson, E. W. (Edward William)',
 'Nelson, Alec',
 'Nelligan, Murray Homer',
 'Nell, William Cooper',
 'Neilson, W. A. (William Allan)',
 'Neill, A. S. (Alexander Sutherland)',
 'Neil, Henry',
 'Neihardt, John Gneisenau',
 'Neef, Frederick Emil',
 'Nearing, Alice Eleanor',
 'Naylor, James Ball',
 'Nordstrom, Ester Blenda',
 'Norman, C. B.',
 'Otto, Karl Ludwig Rudolf',
 'Odonais, Jean Godin des',
 'Omond, G. W. T. (George William Thomson)',
 'Olufs, Harck',
 'Olsen, Alfred Johannes, Jr.',
 'Olmstead, Frederick Law',
 'Olmstead, Denison',
 'Olmstead, Charles Hart',
 'Olmstead, Albert Ten Eyck',
 'Ollefen, L. V. (Lieve van)',
 'Oliver, Joseph Tombs',
 'Oliver, George',
 'Oliphant, S. Grant',
 'Oliphant, Lawrence',
 'Olin, Julia Matilda Lynch',
 'Olin, George Joyce',
 'Oldys, Francis',
 'Oldington, Richard',
 'Old Fogy',
 'Olcott, H. S. (Henry Steel)',
 'Olcott, Charles Sumner',
 'Olah, Gabor',
 'Okenfuss, Lorenz',
 'Oinophilus, Boniface',
 'Peckham, Elizabeth Gifford',
 'Ogden, H. N. (Henry Neely)',
 'Ogden Stewart, Donald',
 'Officer, A British',
 'Office, White Sands Missile Range Public Affairs',
 'Openhaimer, Frants',
 'Oppenheim, Lassa Francis Lawrence',
 'Oppenheim, Max von',
 'Orton, J. W. (James W.)',
 'Otto, Ernst von',
 'Otis, C. H.',
 'Ostwald, Hans Otto August',
 'Ostrander, Stephen',
 'Ostergaard, Vilhelm',
 'Osmun, Thomas Embley',
 'Osmer, W. (William)',
 'Osler, Sir William',
 'Oskison, Hildegarde Hawthorne',
 'Osborne, Richardson',
 'Osborn, Henry Stafford',
 'Osborn, Henry F. (Henry Fairfield)',
 'Orr, Charles E.',
 'Oppenheim, Michael Morris',
 'Orr, Anne Champe',
 'Orndorff, Frank Milliken',
 'Ormsbee, Thomas Hamilton',
 'Ormerod, E. A. (Eleanor Anne)',
 'Ordway, Edith Bertha',
 'Ordonneau, M. (Maurice)',
 'Orcutt, Wm. Dana (William Dana)',
 'Orchestra, Broadway Dance',
 'Orchard, William Edwin',
 'Orban, Balazs',
 'Orage, Alfred Richard',
 'Or-Ot',
 'Odum, Howard W.',
 'Odle, Edwin Vincent',
 'Norman, Wm. B.',
 'Odell, Ernest Gregory',
 'Nyiro, Jozsef',
 'Nycander, Fredrik Axel\u200f',
 'Nyblom, Helena Augusta (Roed)',
 'Nutt, Alfred Trubner',
 'Nurmio, Heikki',
 'Nurmi, Bruno Bernhard',
 'Nunes, Robert',
 'Nunes, Claudio Jose',
 'Nugent, Homer H. (Homer Heath)',
 'Noyes, Margaret Ella',
 'Noyes, J. H. (John Humphrey)',
 'Noyes, Henry Edward',
 'Noyes, Ethel Jane Russell Chesebrough',
 'Novak, Jan Vaclav',
 'Nott, Charles Cooper',
 'Nostradamus, Merlin',
 'Norwood, Robert W.',
 'Norway, George',
 'Norton, M. M. (Morilla Maria)',
 'Norton, Arthur Orlo',
 'Northington, Etta Belle Walker',
 'Northend, Mary H.',
 'Northcote, James Spencer',
 'Norris, Zoe Anderson',
 'Norris, H. L.',
 'Normann, Friedrich Gustav',
 'Normand, Jacques Clary Jean',
 'Nyman, Severi',
 'Nyrop, Christopher',
 'Nyswander, Marie',
 "O'Kelly, Seamus",
 'Ockside, Russ, Knight',
 'Ocantos, Carlos Maria',
 'Oberfield, Bill',
 'Ober, C. K. (Charles Kellogg)',
 'Obdrzalek, Peregrin',
 "O'Shaugnessy, Arthur",
 "O'Shaughnessy, William Brooke",
 "O'Reilly, Augustine J.",
 "O'Pagus, Arry",
 "O'Neale, Lila Morris",
 "O'Meara, J. (James)",
 "O'Mahony, Charles K.",
 "O'Keefe, John",
 "O'Brien, C.",
 "O'Higgins, Harvey J.",
 "O'Hegarty, Patrick Sarsfield",
 "O'Hara, Kenneth",
 "O'Donnell, Elliot",
 "O'Doherty, Morgan, Sir",
 "O'Cotter, Pat",
 "O'Connor, Thomas Power",
 "O'Connor, John L. (John Lawrence)",
 "O'Connor, Edward",
 "O'Brien, George Augustine Thomas",
 "O'Brien, Frank M. (Frank Michael)",
 "O'Brien, Francis Paul",
 'Peck, Robert M.',
 'Picken, Mary Brooks',
 'Peckham, G. W. (George Williams)',
 'Randal, Florence Hamilton',
 'Ray, George Raymond (Holman)',
 'Ray, G. Whitfield (George Whitfield)',
 'Ray, Fan',
 'Rawnsley, Willingham Franklin',
 'Rawnsley, Hardwicke Drummond',
 'Rawlinson, William George',
 'Rawlings, G. B. (Gertrude Burford)',
 'Rawling, L. Bathe (Louis Bathe)',
 'Ravnkilde, Adele Marie',
 'Rausch, Albert Heinrich',
 'Rauhala, Kalle Nikodemus',
 'Rauanheimo, Yrjo',
 'Rathbone, W. (William)',
 'Rasmussen, Knud Johan Victor',
 'Rasières, Isaack de',
 'Rasila, Heikki',
 'Rasanen, Ilmari',
 'Rarey, John Solomon',
 'Raphael, John Nathan Percival',
 'Ransom, R. C.',
 'Ransom, Olive',
 'Ransom, B. H. (Brayton Howard)',
 'Ranney, David James',
 'Rankin, Richard C.',
 'Ranger, Seth',
 'Ranger, Charles',
 'Randolph, Sarah Nicholas',
 'Randolph, Beverly S.',
 'Randolph, Berkeley William',
 'Ray, James Ralph',
 'Raymond, Evelyn Hunt',
 'Raymond, George L. (George Lansing)',
 'Redgrove, Herbert Stanley',
 'Reeve, Arthur Benjamin',
 'Rees, Alfred W.',
 'Reeks, Harry Caulton',
 'Reed, Samuel Burrage',
 'Reed, Louise',
 'Reed, Louis C. M.',
 'Reed, Frederick Richard Cowper',
 'Reed, Earl Howell',
 'Reed, E. T. (Edward Tennyson)',
 'Reed, Chester Albert',
 'Reed, Charles Bert',
 'Redway (Firm)',
 'Redondo, Manuel Ferreira Garcia',
 'Reddaway, W. F. (William Fiddian)',
 'Raymond, Rossiter Worthington',

In [66]:
authors["alias"].isna().sum()

np.int64(17426)

In [67]:
authors["alias"].notna().sum()

np.int64(8651)

In [70]:
authors[
    authors["author"] == "Madison, James"
][["author", "alias", "aliases"]]

            author  ...                              aliases
11  Madison, James  ...  United States President (1809-1817)

[1 rows x 3 columns]

In [72]:
from tt_gutenberg.authors import *

list_authors(by_languages=True, alias=True)

['Grimm, Jacob Ludwig Carl',
 'Grimm, Wilhelm Carl',
 'Andersen, Hans Christian',
 "Wilde, Oscar Fingal O'Flahertie Wills",
 'Stevenson, R. L. (Robert Louis)',
 'Alighieri, Dante',
 'Όμηρος',
 'Poe, Edgar Allen',
 'Πλάτων',
 'Swift, J. (Jonathan)',
 'De Maupassant, Guy',
 'Chaney, John Griffith',
 'Dodgson, Charles Lutwidge',
 'Von Schmid, Christoph',
 'Wells, Herbert George',
 'Rollan, R.',
 'Darwin, Charles Robert',
 'Crayon, Geoffrey',
 'Descartes, Rene',
 'Gloux, Olivier',
 'Mill, J. S. (John Stuart)',
 'Harte, Francis Bret',
 'Wallace, Lewis',
 'Heine, H. (Heinrich)',
 'Curwood, James-Oliver',
 'Ohnet, Jorge',
 'Branch, Stephen',
 'Malot, Hector-Henri',
 'Bunyan, Johann',
 'Whitman, Walter',
 'Buonarroti, Michelangelo',
 'Michelet, J.',
 'Racine, Jean Baptiste',
 'Reuter, Heinrich Ludwig Christian Friedrich',
 'Ruskin, J. (John)',
 'Strindberg, Johan August',
 'Merimee, Prosper',
 'Engels, Frederick',
 'Chaucer, Jeffrey',
 'Augustine, Saint',
 '孔子',
 'Murger, Henry',
 'Daudet, Louis Marie Alphonse',
 'Erasmus, of Rotterdam',
 'Tennyson, Alfred Lord',
 'Storm, Hans Theodor Woldsen',
 'Diderot, Pantophile',
 'Weyman, Stanley J. (Stanley John)',
 'Maranan, Apolinario Mabini y',
 'Verlaine, Paul Marie',
 'Warneford, Lieutenant',
 'Donquichote, Marguerite',
 'Hawkins, Anthony Hope',
 'Hauptmann, Gerhart Johann Robert',
 'Longfellow, Henry W.',
 'Shelley, P. B. (Percy Bysshe)',
 'Carlyle, T. (Thomas)',
 'Collins, William Wilkie',
 'Keller, Gotfryd',
 'Key, Ellen Karolina Sofia',
 'Válmíki',
 'Brehm, A. E. (Alfred Edmund)',
 'Goldsmit, Oliver',
 'Wassermann, Jacob',
 'Freitag, Gustav',
 'Bazin, Rene',
 'Long, William Joseph',
 'Campe, J. H. (Joachim Heinrich)',
 'Stevenson, Burton E.',
 'Steiner, Rudolph',
 'Zschokke, Johann Heinrich Daniel',
 'Barnivelt, Esdras',
 'Peltonen, Vihtori',
 'Haeckel, Ernst Heinrich Philipp August',
 'Couperus, Louis Marie Anne',
 'Bush, W. (Wilhelm)',
 'Sardou, V. (Victorien)',
 'Sallustius Crispus, Gaius',
 'Nodier, Jean Charles Emmanuel',
 'Kock, Charles Paul de',
 'Dekker, Eduard Douwes',
 'Brown, Giorgio Rossi',
 'Lessing, G. E.',
 'Boethius, Anicius Manlius Severinus',
 'Ewald, Karl',
 'Jacobsen, Jens Peter',
 'Verhaeren, Émile',
 'Michaelis, Richard C.',
 'Charles, Elisabeth Rundle',
 'Della Porta, Giambattista',
 'Yorick, Mr.',
 'Ford, Ricardo',
 'Westermarck, Edvard Alexander',
 'Montalte, Louis de',
 'Ceynowa, Florian Stanislaw',
 'Woolsey, Sarah Chauncey',
 'Junghuhn, F. W.',
 'Bell, Gertrude Margaret Lowthian',
 'Lemercier, Eugene Emmanuel',
 'Plautus, Marcus Accius',
 'Cotterill, Henry Bernard',
 'Gozlan, Leon',
 'Arrhenius, Svante August',
 'Falkner, J. Meade (John Meade)',
 'Davis, Frederick Hadland',
 'Young, Artur',
 'Sayer, Geo. J.',
 'Delepierre, Joseph Octave',
 'Lie, Jonas Lauritz Idemil',
 'Spence, James Lewis Thomas Chalmers',
 'Strachey, Giles Lytton',
 'Hartmann, F. (Franz)',
 'Jones, Alfred Ernest',
 'Hull, Edith Maude',
 'De Fornaro, Carlo',
 'De Gorostiza, Manuel Eduardo',
 'Forster, Edward Morgan',
 'Mitre, Bartolome',
 'Cousin, Vittorio',
 'Planck, Max Karl Ernst Ludwig',
 'Raleigh, Sir Walter Alexander',
 'Huizinga, J. (Johan)',
 'Jones, Raymond F. (Raymond Fisher)',
 'Rakosi, Viktor',
 'De Wit, Augusta',
 'Wyss, J. D. (Johann David)',
 'Moinaux, J. (Jules)',
 'Mitchell, J. A. (John Ames)',
 'Harting, P. (Pieter)',
 'Papini, G. (Giovanni)',
 'Faccio, Rina',
 'Li, Ya-ko',
 'Lermina, Jules Hippolyte',
 'Moisa, Dorin T.',
 'Faraday, M. (Michael)',
 "O'Connor, John Charles",
 'Wells, David A.',
 'Scheepstra, Hendericus',
 'Lemonnier, Antoine Louis Camille',
 'Weule, K. (Karl)',
 'Seume, J. G. (Johann Gottfried)',
 'Boyer, A. (Abel)',
 'Bougainville, comte de (Louis-Antoine)',
 'Finnemore, J. (John)',
 'Gjellerup, Karl Adolph',
 'Churton Braby, Maud',
 'Uzanne, Louis Octave',
 'Hegel, G. W. F. (Georg Wilhelm Friedrich)',
 'Urpia, Jaime Luciano Balmes',
 'Lowell, Edward Jackson',
 'Heer, Jakob Christoph',
 'Urbanus',
 'Sewell, Ana',
 'Figuier, Guillaume-Louis',
 'Veniero, Lorenzo',
 "D'Holbach, Baron",
 'Borrow, George Henry',
 'Bang, Herman Joachim',
 'Iron, Ralph',
 'Fletcher, Joseph Smith',
 'Shackleton, E. H. (Ernest Henry), Sir',
 'Bates, Harriet Leonora Vose',
 'Wilder, Thornton Niven',
 'Vanderem, Fernand',
 'Menant, Dauphine',
 'Ostwald, Friedrich Wilhelm',
 'Crowther, S. (Samuel)',
 'Wilberforce, W. (William)',
 'Seignobos, Ch. (Charles)',
 'Hemon, Louis',
 'Stedman, Jean-Gabriel',
 'Luska, Sidney',
 'Ingelius, A. G.',
 'Hemmer, Jarl Robert',
 'Serner, Gunnar',
 'Huxley, T. H. (Thomas Henry)',
 'Lundegard, Axel',
 'Ingram, Eleanor Marie',
 'Valois, Marguerite de',
 'Banfield, Edmund James',
 'Loránd, Arnold',
 'Lindman, Voldemar',
 'Cherbuliez, Charles Victor',
 'Lock, John',
 'Giacosa, G. (Giuseppe)',
 'Fechner, G. Th. (Gustav Theodor)',
 'Ernst, Otto',
 'Schlemihl, Peter',
 'Tweedsmuir, John Buchan, Baron',
 'Liszt, F. (Franz)',
 'Jensen, Johannes Vilhelm',
 'Bebel, Auguste',
 'Brillat-Savarin, Jean Anthelme',
 'Obama, Barack Hussein, II',
 'Pluschow, Gunther',
 'Linnaeus, Carolus',
 'Stoker, Abraham',
 'Lindsay, T. M. (Thomas Martin)',
 'Goose, Mary Susan',
 'Beck, James Montgomery',
 'Stallman, Richard M.',
 'Ubaldino, Petruccio',
 'Borel, Jean',
 'Chevalier, Michael',
 'Glyn, Elinor Sutherland',
 'Lorenc, Frantisek Vladimir',
 'Jacobs, William Wymark',
 'Jagor, Andreas Fedor',
 'Fewkes, J. Walter (Jesse Walter)',
 'Beach, Rex Ellingwood',
 'Crawford, Francis Marion',
 'Boothby, Guy Newell',
 'Ferri, Enrique',
 'Hayes, Charles Frederic',
 'Lonnrot, Elias',
 'Paine, Walter Lionel',
 'Goffic, Charles Le',
 'Brazil. Commissao, Exposicao internacioncal de borracha de New York, 1912',
 'Polko, E. (Elise)',
 'Schopfer, Jean',
 'Oksanen, A.',
 'Junius',
 'Baruch, Moses',
 'Delpit, Marc-Adrien',
 'Ritchie, F. (Francis)',
 'Marcus Vitruvius Pollio',
 'Morley, Christopher Darlington',
 'Roessler, Erwin William Eugene',
 'Philippe, Ch.-L. (Charles-Louis)',
 'Watson, John',
 'Runa',
 'Disraeli, B. (Benjamin), Earl of Beaconsfield',
 'Lasker, Eduard',
 'Coote, Miss',
 'Runeberg, J. L. (Johan Ludvig)',
 'Nansen, P. (Peter)',
 'Blanc, H. (Henry)',
 'Latzko, Adolf Andreas',
 'Newton, Sir Isaac',
 'Voß, Richard',
 'Sinjohn, John',
 'Greenfield, Gulielmus',
 'Collado, D. (Diego)',
 'Keller, Helen Adams',
 'Drago, Luis Maria',
 'Blanche, August Teodor',
 'Slousch, Nahum',
 'Gubernatis, Angelo de, conte',
 'Fry, Sheila Kaye-Smith',
 'Ellis, Henry Havelock',
 'Soderhjelm, Alma',
 '谷崎潤一郎',
 'Wallace, Richard Horatio Edgar',
 'Bushnell, Curtis Clark',
 'Morne, Arvid',
 'Revesz, Bela',
 'Pfeiffer, Ida Reyer',
 'Kyrburg, Fritz von der',
 'Hobson, John Atkinson',
 'Edwardes, Edward Tickner',
 'Donner, O. (Otto)',
 'Maundeville, John',
 'Burckhardt, Jakob Christoph',
 'Alcock, D.',
 'Hocker, Gustav',
 'Mosso, Angelo',
 'Labaigt, Laurent',
 'Aguinaldo y Famy, Emilio',
 'Edwards, O. M., Sir',
 '曹雪芹',
 'Eden, Charles Henry',
 'Tavaststjerna, Karl A. (Karl August)',
 'Bull, Jakob B.',
 'Birt, Theodorus',
 'Rollin, Carol',
 'Friis, Jens Andreas',
 'Gaboriau, Émile',
 'Smith, Sarah',
 'Pennell, Theodore Leighton',
 'Bernard, Paul',
 'Peard, Frances M. (Frances Mary)',
 'Dodge, M. E. (Mary Elizabeth)',
 'Kroeh, Charles F.',
 'Cameron, V. L. (Verney Lovett)',
 'Carlet, Pierre',
 'Roux, Hugues le',
 'Beyrich, Clementine (Helm), Frau',
 'Busch, Julius Hermann Moritz',
 'Endle, S. (Sidney)',
 'Von Liebig, Justus, Freiherr',
 'Gasson, Herbert N. (Herbert Newton)',
 'Maspero, Gaston Camille Charles, Sir',
 'Enochs, James Bryon',
 'Pegge, S. (Samuel)',
 'Aneurin',
 'Caius Julius Phaedrus',
 'Caspari, Karl Heinrich',
 'Corroyer, Édouard',
 'Wecksell, Josef Julius',
 'Gunnarsons, Gunnars',
 'Δημοσθένης',
 'Wedekind, Benjamin Franklin',
 'Guerrazzi, F. D. (Francesco Domenico)',
 'Cairon, Claude Antoine Jules',
 'Blommaert, Willem',
 'Rebecque, Henri Benjamin Constant de',
 'Guthrie, Thomas Anstey',
 'Murray, M. A. (Margaret Alice)',
 'Kloosterman, Jan Ritskes',
 'Mallanaga',
 'Souvestre, Emile',
 'Tourgee, Albion Winegar',
 'Malatesta, Enrico',
 'Robida, A. (Albert)',
 'Anderson, James Drummond',
 'Norris, Benjamin Franklin',
 'Tegner, Esaias',
 'Topelius, Toini Mathilda',
 'Sabatini, R.',
 'Hackluyt, Richard',
 'Holmes, Gordon',
 'Benoit, Pierre',
 'Гончаров, Иван Александрович',
 'Wangemann, Eduard Carl Otto',
 'Kafka, F. (Franz)',
 'Massenet, J. (Jules)',
 'Huch, Ricarda Octavia',
 'Mainwaring, C. L.',
 'Gurdon, Philip Richard Thornhagh',
 'Pearce, Joseph Henry',
 'Pearce, E. H. (Ernest Harold)',
 'Overstreet, Harry Allen',
 'Pain, Thomas',
 'Overseer',
 'Overton, J. H. (John Henry)',
 'Peck, J. M. (John Mason)',
 'Pain, Barry Eric Odell',
 'Peabody, F. W. (Frederick William)',
 'Peabody, E. P. (Elizabeth Palmer)',
 'Pear, Tom Hatherley',
 'Peck, R. H.',
 'Peano, G. (Giuseppe)',
 'Pailleron, Édouard Jules Henri',
 'Overton, Grant Martin',
 'Peake, Harold John Edward',
 'Pace, Thomas C.',
 'Peck, J. L. (John Lord)',
 'Pearce, William P. (William Peter)',
 'Packard, Robert Lewis',
 'Pearson, Arthur Cyril',
 'Packeny, Elsa Maria',
 'Paavo-Kallio, Esaias',
 'Pearson, Charles Henry',
 'Pearse, H. H. S. (Henry Hiram Steere)',
 'P. B. St.',
 'Ozaki, Yukio, Madame',
 'Pearson, E. L. (Edmund Lester)',
 'Oxley, James M. (James Macdonald)',
 'Paddock, Buckley B.',
 'Pearse, Guy Mark',
 'Owen, Robert Latham',
 'Pears, James R.\u200f',
 'Paden, Clifton',
 'Paes, Domingo',
 'Pearson, Thomas Gilbert',
 'Pease, A. E. (Alfred Edward), Sir',
 'Owen, John, Rector of Paglesham, Essex',
 'Paez, Ramon',
 'Paganino, Rodrigo Botelho da Fonseca',
 'Owen, Jean Allan',
 'Pearn, Violet A.',
 'Page, Gerald Wilburn',
 'Paget, Violet',
 'Peck, Annie Smith',
 'Peck, George Wilbur',
 'Payne-Gallwey, Ralph William Frankland, Sir, bart.',
 'Pallander, Gunnar',
 'Payne, Paul Lawrence',
 'Partridge, George Everett',
 'Paris, J. A. (John Ayrton)',
 'Parrish, George Dillwyn',
 'Paredes, Manuel Rigoberto',
 'Parry, Edwin Francis',
 'Pardee, Richard Gay',
 'Parsons, B. (Benjamin)',
 'Parsons, S. B.',
 'Parsons, Wm. Barclay (William Barclay)',
 'Partridge, Edward Bellamy',
 'Paquiro',
 'Payne, Buckner Harrison',
 'Pascal, Theophile',
 'Paske, Charles Thomas',
 'Passos, John Dos',
 'Patanjali',
 'Panton, Jane Ellen',
 'Patch, Edith Marion',
 'Patchin, Frank Glines',
 'Paternoster, George Sidney,',
 'Panshin, Alexis Adams',
 'Park, J. R. (John Ranicar)',
 'Park, James Alan, Sir',
 'Park, Robert E.',
 'Parker, Amos Andrew',
 'Parkman, F. (Francis)',
 'Parker, Louis N. (Louis Napoleon)',
 'Parker, L. S. (Lester Shepard)',
 'Parkman, Mary R.',
 'Parker, James Gordon',
 'Parley, Peter',
 'Parker, J. H. (John Henry)',
 'Parker, Henry',
 'Parker, George, Earl of Macclesfield',
 'Parliament, British',
 'Parloa, Miss (Maria)',
 'Parmanen, Eino I.',
 'Parker, E. H. (Edward Harper)',
 'Parnel, Thomas',
 'Parquet, Marguerite Du',
 'Parker, Dorothy Rothschild',
 'Parker, DeWitt H. (DeWitt Henry)',
 'Parr, Harriet',
 'Parr, Mrs. (Louisa Taylor)',
 'Patmore, Coventry Kersey Dighton',
 'Patmore, Peter George',
 'Paton, Andrew Archibald',
 'Parker, Richard Barry',
 'Palgrave, Francis T.',
 'Patterson, John Henry',
 'Patteson, Susanna Louise',
 'Palffy, Albert',
 'Paul, Ford',
 'Paul, Herbert Woodfield',
 'Paul, Sir John Dean, bart.',
 'Pauli, Simon',
 'Palacios, Pedro Bonifacio',
 'Pakiser, Louis Charles',
 'Pakh, Albert',
 'Paulton, Edward Antonio',
 'Paxson, Frederic Logan',
 'Paxton, John D.',
 'Paivarinta, Pietari',
 'Pay, Committee on Railway Mail',
 'Painter, Franklin Verzelius Newton',
 'Payen, Jean-François',
 'Paine, Ralph D. (Ralph Delahaye)',
 'Patterson, J. M. (Joseph Medill)',
 'Pallme, Ignatius',
 'Panizza, Oscar',
 'Palmer, Alice Elvira Freeman',
 'Panin, I. (Ivan)',
 'Pangloss, docteur',
 'Palmer, William Thomas',
 'Palmer, W. Scott (William Scott)',
 'Paton, John G.',
 'Palmer, Josephine L.',
 'Patrat, J. (Joseph)',
 'Palmer, John Leslie',
 'Palmer, Herbert Edward',
 'Palmer, H. E. (Harold E.)',
 'Patricio, Antonio',
 'Patricio, Ladislau',
 'Patricola',
 'Pattee, George Kynett',
 'Palmer, E. H. (Edward Henry)',
 'Palmer, Donald Ellsworth',
 'Palmer, Austin Norman',
 'Patterson, Anne Virginia Sharpe',
 'Patterson, Caleb Perry',
 'A Bushman',
 'Ohrwalder, Joseph',
 'Ottolini, Vittore',
 'Newark, N.J. College of Engineering',
 'Nicklin, John Arnold',
 'Nicholson, Joseph Shield',
 'Nicholson, James Bartram',
 'Nicholson, H. Alleyne (Henry Alleyne)',
 'Nichols, W. T.',
 'Nichols, Robert Malise Bowyer',
 'Nichols, James Thomas',
 'Nichols, James M.',
 'Nichols, James Lawrence',
 'Nicaise, Charles-Louis Auguste',
 'Newton, R. Heber (Richard Heber)',
 'Newton, John',
 'Newton, Alexander Herritage',
 'Newte, Horace Wykeham Can',
 'Newsholme, Sir Arthur',
 'Newmann, Louis',
 'Newman, F. W. (Francis William)',
 'Newman, Edward Manuel',
 'Newlin, William Henry',
 'Newlin, Katharine',
 'Newland, Henry Garrett',
 'Newell, Robert Henry',
 'Newell, P. S. (Peter S.)',
 'Newell, M. Moyca',
 'Newell, Geo. E.',
 'Newbigin, Marion Isabel',
 'Newberry, Percy Edward',
 'Nicolas, Lady Sarah Davison',
 'Nicolay, John George',
 'Nicolini, Giovanni Battista',
 'Noah, Mordecai Manuel',
 'Nordlund, K. (Karl)',
 'Nordhoff, Charles Bernard',
 'Nordenskiold, A. E. (Adolf Erik)',
 'Nordberg, Carl Edin',
 'Nonagenarian',
 'Noll, R. C.',
 'Nolan, Edward Henry',
 'Nogent, Guibert de',
 'Noe, Sydney Philip',
 'Noe, James Thomas Cotton',
 'Nobre, Antonio',
 'Noble, Theophilus Charles',
 'Nizam-ud-din-Ahmad',
 'Nieboer, Herman Jeremias',
 'Nixon, Oliver Woodson',
 'Niven, Frederick John',
 'Nitsch, Helen Alice Matthews',
 'Nisbet, James Hume',
 'Nilsson, Martin Persson',
 'Nilsen, Eric',
 'Niewadomska, Cecylia',
 'Niemi, A. R. (Aukusti Robert)',
 'Nielsen, Jens Peter Zakarias',
 'Nielsen, Anton',
 'Niederlein, Gustav',
 'Niebuhrius, B. G. (Barthold Georg)',
 'Newberry, Fanny E. (Fanny Ellsworth)',
 'New York detective',
 'Norman, B. M. (Benjamin Moore)',
 'New York Historical Association',
 'Nasmith, George G. (George Gallie)',
 'Nash, Mrs. William H.',
 'Naquet, A. (Alfred)',
 'Napton, W. B. (William Barclay)',
 'Nankivell, Edward James',
 'Name, Addison Van',
 'Nagy, Ignacz',
 'Myers, Philip Van Ness',
 'Myers, Frederic William Henry',
 'Myddleton, William Henry',
 'Muzzey, Artemas Bowers',
 'Mutzenberg, Chas. G.',
 'Mustakallio, Johannes',
 'Musson, S. C. (Spencer C.)',
 'Mussey, Reuben Dimond',
 'Musgrave, Dr. (Samuel)',
 'Musel, Robert',
 'Muse, Ben',
 'Murrey, Thomas Jefferson',
 'Murray, William Henry Harrison',
 'Murray, Thomas Boyles',
 'Murray, Robert Fuller',
 'Murray, James A. H.',
 'Murray, Henry Anthony',
 'Murray, H. Kincaid',
 'Murray, Elsie Riach',
 'Murray, David Leslie',
 'Nassau, R. H. (Robert Hamill)',
 'Nathan, Annie',
 'Nathorst, Alfred Gabriel',
 'Nepomuk',
 'New York (Colony). Legislative Council',
 'Neville, Kris Ottman',
 'Neville, Emily Cheney',
 'Nevill, Ralph Henry',
 'Neveux, Pol Louis',
 'Neuman, Nancy W. Hawkins',
 'Neufeld, Carl',
 'Netscher, A. D. van der gon',
 'Netherton, Ross D. (Ross De Witt)',
 'Nessmuk',
 'Neralc, Jenny',
 'Nepoty, Lucien',
 'Nelson, W. S.',
 'National Live Stock & Meat Board',
 'Nelson, Hector William',
 'Nelson, E. W. (Edward William)',
 'Nelson, Alec',
 'Nelligan, Murray Homer',
 'Nell, William Cooper',
 'Neilson, W. A. (William Allan)',
 'Neill, A. S. (Alexander Sutherland)',
 'Neil, Henry',
 'Neihardt, John Gneisenau',
 'Neef, Frederick Emil',
 'Nearing, Alice Eleanor',
 'Naylor, James Ball',
 'Nordstrom, Ester Blenda',
 'Norman, C. B.',
 'Otto, Karl Ludwig Rudolf',
 'Odonais, Jean Godin des',
 'Omond, G. W. T. (George William Thomson)',
 'Olufs, Harck',
 'Olsen, Alfred Johannes, Jr.',
 'Olmstead, Frederick Law',
 'Olmstead, Denison',
 'Olmstead, Charles Hart',
 'Olmstead, Albert Ten Eyck',
 'Ollefen, L. V. (Lieve van)',
 'Oliver, Joseph Tombs',
 'Oliver, George',
 'Oliphant, S. Grant',
 'Oliphant, Lawrence',
 'Olin, Julia Matilda Lynch',
 'Olin, George Joyce',
 'Oldys, Francis',
 'Oldington, Richard',
 'Old Fogy',
 'Olcott, H. S. (Henry Steel)',
 'Olcott, Charles Sumner',
 'Olah, Gabor',
 'Okenfuss, Lorenz',
 'Oinophilus, Boniface',
 'Peckham, Elizabeth Gifford',
 'Ogden, H. N. (Henry Neely)',
 'Ogden Stewart, Donald',
 'Officer, A British',
 'Office, White Sands Missile Range Public Affairs',
 'Openhaimer, Frants',
 'Oppenheim, Lassa Francis Lawrence',
 'Oppenheim, Max von',
 'Orton, J. W. (James W.)',
 'Otto, Ernst von',
 'Otis, C. H.',
 'Ostwald, Hans Otto August',
 'Ostrander, Stephen',
 'Ostergaard, Vilhelm',
 'Osmun, Thomas Embley',
 'Osmer, W. (William)',
 'Osler, Sir William',
 'Oskison, Hildegarde Hawthorne',
 'Osborne, Richardson',
 'Osborn, Henry Stafford',
 'Osborn, Henry F. (Henry Fairfield)',
 'Orr, Charles E.',
 'Oppenheim, Michael Morris',
 'Orr, Anne Champe',
 'Orndorff, Frank Milliken',
 'Ormsbee, Thomas Hamilton',
 'Ormerod, E. A. (Eleanor Anne)',
 'Ordway, Edith Bertha',
 'Ordonneau, M. (Maurice)',
 'Orcutt, Wm. Dana (William Dana)',
 'Orchestra, Broadway Dance',
 'Orchard, William Edwin',
 'Orban, Balazs',
 'Orage, Alfred Richard',
 'Or-Ot',
 'Odum, Howard W.',
 'Odle, Edwin Vincent',
 'Norman, Wm. B.',
 'Odell, Ernest Gregory',
 'Nyiro, Jozsef',
 'Nycander, Fredrik Axel\u200f',
 'Nyblom, Helena Augusta (Roed)',
 'Nutt, Alfred Trubner',
 'Nurmio, Heikki',
 'Nurmi, Bruno Bernhard',
 'Nunes, Robert',
 'Nunes, Claudio Jose',
 'Nugent, Homer H. (Homer Heath)',
 'Noyes, Margaret Ella',
 'Noyes, J. H. (John Humphrey)',
 'Noyes, Henry Edward',
 'Noyes, Ethel Jane Russell Chesebrough',
 'Novak, Jan Vaclav',
 'Nott, Charles Cooper',
 'Nostradamus, Merlin',
 'Norwood, Robert W.',
 'Norway, George',
 'Norton, M. M. (Morilla Maria)',
 'Norton, Arthur Orlo',
 'Northington, Etta Belle Walker',
 'Northend, Mary H.',
 'Northcote, James Spencer',
 'Norris, Zoe Anderson',
 'Norris, H. L.',
 'Normann, Friedrich Gustav',
 'Normand, Jacques Clary Jean',
 'Nyman, Severi',
 'Nyrop, Christopher',
 'Nyswander, Marie',
 "O'Kelly, Seamus",
 'Ockside, Russ, Knight',
 'Ocantos, Carlos Maria',
 'Oberfield, Bill',
 'Ober, C. K. (Charles Kellogg)',
 'Obdrzalek, Peregrin',
 "O'Shaugnessy, Arthur",
 "O'Shaughnessy, William Brooke",
 "O'Reilly, Augustine J.",
 "O'Pagus, Arry",
 "O'Neale, Lila Morris",
 "O'Meara, J. (James)",
 "O'Mahony, Charles K.",
 "O'Keefe, John",
 "O'Brien, C.",
 "O'Higgins, Harvey J.",
 "O'Hegarty, Patrick Sarsfield",
 "O'Hara, Kenneth",
 "O'Donnell, Elliot",
 "O'Doherty, Morgan, Sir",
 "O'Cotter, Pat",
 "O'Connor, Thomas Power",
 "O'Connor, John L. (John Lawrence)",
 "O'Connor, Edward",
 "O'Brien, George Augustine Thomas",
 "O'Brien, Frank M. (Frank Michael)",
 "O'Brien, Francis Paul",
 'Peck, Robert M.',
 'Picken, Mary Brooks',
 'Peckham, G. W. (George Williams)',
 'Randal, Florence Hamilton',
 'Ray, George Raymond (Holman)',
 'Ray, G. Whitfield (George Whitfield)',
 'Ray, Fan',
 'Rawnsley, Willingham Franklin',
 'Rawnsley, Hardwicke Drummond',
 'Rawlinson, William George',
 'Rawlings, G. B. (Gertrude Burford)',
 'Rawling, L. Bathe (Louis Bathe)',
 'Ravnkilde, Adele Marie',
 'Rausch, Albert Heinrich',
 'Rauhala, Kalle Nikodemus',
 'Rauanheimo, Yrjo',
 'Rathbone, W. (William)',
 'Rasmussen, Knud Johan Victor',
 'Rasières, Isaack de',
 'Rasila, Heikki',
 'Rasanen, Ilmari',
 'Rarey, John Solomon',
 'Raphael, John Nathan Percival',
 'Ransom, R. C.',
 'Ransom, Olive',
 'Ransom, B. H. (Brayton Howard)',
 'Ranney, David James',
 'Rankin, Richard C.',
 'Ranger, Seth',
 'Ranger, Charles',
 'Randolph, Sarah Nicholas',
 'Randolph, Beverly S.',
 'Randolph, Berkeley William',
 'Ray, James Ralph',
 'Raymond, Evelyn Hunt',
 'Raymond, George L. (George Lansing)',
 'Redgrove, Herbert Stanley',
 'Reeve, Arthur Benjamin',
 'Rees, Alfred W.',
 'Reeks, Harry Caulton',
 'Reed, Samuel Burrage',
 'Reed, Louise',
 'Reed, Louis C. M.',
 'Reed, Frederick Richard Cowper',
 'Reed, Earl Howell',
 'Reed, E. T. (Edward Tennyson)',
 'Reed, Chester Albert',
 'Reed, Charles Bert',
 'Redway (Firm)',
 'Redondo, Manuel Ferreira Garcia',
 'Reddaway, W. F. (William Fiddian)',
 'Raymond, Rossiter Worthington',

In [73]:
authors[
    authors["alias"].isin(
        [
            "Wilde, Oscar Fingal O'Flahertie Wills",
            "Parliament, British",
            "National Live Stock & Meat Board"
        ]
    )
][["author", "alias", "birthdate", "deathdate"]]

                                   author  ... deathdate
101                          Wilde, Oscar  ...    1900.0
2212            Great Britain. Parliament  ...       NaN
21836  National Live Stock and Meat Board  ...       NaN

[3 rows x 4 columns]

In [1]:
from tt_gutenberg.authors import *

list_authors(by_languages=True, alias=True)

['Grimm, Jacob Ludwig Carl',
 'Grimm, Wilhelm Carl',
 'Andersen, Hans Christian',
 "Wilde, Oscar Fingal O'Flahertie Wills",
 'Stevenson, R. L. (Robert Louis)',
 'Alighieri, Dante',
 'Όμηρος',
 'Poe, Edgar Allen',
 'Πλάτων',
 'Swift, J. (Jonathan)',
 'De Maupassant, Guy',
 'Chaney, John Griffith',
 'Dodgson, Charles Lutwidge',
 'Von Schmid, Christoph',
 'Wells, Herbert George',
 'Rollan, R.',
 'Darwin, Charles Robert',
 'Crayon, Geoffrey',
 'Descartes, Rene',
 'Gloux, Olivier',
 'Mill, J. S. (John Stuart)',
 'Harte, Francis Bret',
 'Wallace, Lewis',
 'Heine, H. (Heinrich)',
 'Curwood, James-Oliver',
 'Ohnet, Jorge',
 'Branch, Stephen',
 'Malot, Hector-Henri',
 'Bunyan, Johann',
 'Whitman, Walter',
 'Buonarroti, Michelangelo',
 'Michelet, J.',
 'Racine, Jean Baptiste',
 'Reuter, Heinrich Ludwig Christian Friedrich',
 'Ruskin, J. (John)',
 'Strindberg, Johan August',
 'Merimee, Prosper',
 'Engels, Frederick',
 'Chaucer, Jeffrey',
 'Augustine, Saint',
 '孔子',
 'Murger, Henry',
 'Daudet, Louis Marie Alphonse',
 'Erasmus, of Rotterdam',
 'Tennyson, Alfred Lord',
 'Storm, Hans Theodor Woldsen',
 'Diderot, Pantophile',
 'Weyman, Stanley J. (Stanley John)',
 'Maranan, Apolinario Mabini y',
 'Verlaine, Paul Marie',
 'Warneford, Lieutenant',
 'Donquichote, Marguerite',
 'Hawkins, Anthony Hope',
 'Hauptmann, Gerhart Johann Robert',
 'Longfellow, Henry W.',
 'Shelley, P. B. (Percy Bysshe)',
 'Carlyle, T. (Thomas)',
 'Collins, William Wilkie',
 'Keller, Gotfryd',
 'Key, Ellen Karolina Sofia',
 'Válmíki',
 'Brehm, A. E. (Alfred Edmund)',
 'Goldsmit, Oliver',
 'Wassermann, Jacob',
 'Freitag, Gustav',
 'Bazin, Rene',
 'Long, William Joseph',
 'Campe, J. H. (Joachim Heinrich)',
 'Stevenson, Burton E.',
 'Steiner, Rudolph',
 'Zschokke, Johann Heinrich Daniel',
 'Barnivelt, Esdras',
 'Peltonen, Vihtori',
 'Haeckel, Ernst Heinrich Philipp August',
 'Couperus, Louis Marie Anne',
 'Bush, W. (Wilhelm)',
 'Sardou, V. (Victorien)',
 'Sallustius Crispus, Gaius',
 'Nodier, Jean Charles Emmanuel',
 'Kock, Charles Paul de',
 'Dekker, Eduard Douwes',
 'Brown, Giorgio Rossi',
 'Lessing, G. E.',
 'Boethius, Anicius Manlius Severinus',
 'Ewald, Karl',
 'Jacobsen, Jens Peter',
 'Verhaeren, Émile',
 'Michaelis, Richard C.',
 'Charles, Elisabeth Rundle',
 'Della Porta, Giambattista',
 'Yorick, Mr.',
 'Ford, Ricardo',
 'Westermarck, Edvard Alexander',
 'Montalte, Louis de',
 'Ceynowa, Florian Stanislaw',
 'Woolsey, Sarah Chauncey',
 'Junghuhn, F. W.',
 'Bell, Gertrude Margaret Lowthian',
 'Lemercier, Eugene Emmanuel',
 'Plautus, Marcus Accius',
 'Cotterill, Henry Bernard',
 'Gozlan, Leon',
 'Arrhenius, Svante August',
 'Falkner, J. Meade (John Meade)',
 'Davis, Frederick Hadland',
 'Young, Artur',
 'Sayer, Geo. J.',
 'Delepierre, Joseph Octave',
 'Lie, Jonas Lauritz Idemil',
 'Spence, James Lewis Thomas Chalmers',
 'Strachey, Giles Lytton',
 'Hartmann, F. (Franz)',
 'Jones, Alfred Ernest',
 'Hull, Edith Maude',
 'De Fornaro, Carlo',
 'De Gorostiza, Manuel Eduardo',
 'Forster, Edward Morgan',
 'Mitre, Bartolome',
 'Cousin, Vittorio',
 'Planck, Max Karl Ernst Ludwig',
 'Raleigh, Sir Walter Alexander',
 'Huizinga, J. (Johan)',
 'Jones, Raymond F. (Raymond Fisher)',
 'Rakosi, Viktor',
 'De Wit, Augusta',
 'Wyss, J. D. (Johann David)',
 'Moinaux, J. (Jules)',
 'Mitchell, J. A. (John Ames)',
 'Harting, P. (Pieter)',
 'Papini, G. (Giovanni)',
 'Faccio, Rina',
 'Li, Ya-ko',
 'Lermina, Jules Hippolyte',
 'Moisa, Dorin T.',
 'Faraday, M. (Michael)',
 "O'Connor, John Charles",
 'Wells, David A.',
 'Scheepstra, Hendericus',
 'Lemonnier, Antoine Louis Camille',
 'Weule, K. (Karl)',
 'Seume, J. G. (Johann Gottfried)',
 'Boyer, A. (Abel)',
 'Bougainville, comte de (Louis-Antoine)',
 'Finnemore, J. (John)',
 'Gjellerup, Karl Adolph',
 'Churton Braby, Maud',
 'Uzanne, Louis Octave',
 'Hegel, G. W. F. (Georg Wilhelm Friedrich)',
 'Urpia, Jaime Luciano Balmes',
 'Lowell, Edward Jackson',
 'Heer, Jakob Christoph',
 'Urbanus',
 'Sewell, Ana',
 'Figuier, Guillaume-Louis',
 'Veniero, Lorenzo',
 "D'Holbach, Baron",
 'Borrow, George Henry',
 'Bang, Herman Joachim',
 'Iron, Ralph',
 'Fletcher, Joseph Smith',
 'Shackleton, E. H. (Ernest Henry), Sir',
 'Bates, Harriet Leonora Vose',
 'Wilder, Thornton Niven',
 'Vanderem, Fernand',
 'Menant, Dauphine',
 'Ostwald, Friedrich Wilhelm',
 'Crowther, S. (Samuel)',
 'Wilberforce, W. (William)',
 'Seignobos, Ch. (Charles)',
 'Hemon, Louis',
 'Stedman, Jean-Gabriel',
 'Luska, Sidney',
 'Ingelius, A. G.',
 'Hemmer, Jarl Robert',
 'Serner, Gunnar',
 'Huxley, T. H. (Thomas Henry)',
 'Lundegard, Axel',
 'Ingram, Eleanor Marie',
 'Valois, Marguerite de',
 'Banfield, Edmund James',
 'Loránd, Arnold',
 'Lindman, Voldemar',
 'Cherbuliez, Charles Victor',
 'Lock, John',
 'Giacosa, G. (Giuseppe)',
 'Fechner, G. Th. (Gustav Theodor)',
 'Ernst, Otto',
 'Schlemihl, Peter',
 'Tweedsmuir, John Buchan, Baron',
 'Liszt, F. (Franz)',
 'Jensen, Johannes Vilhelm',
 'Bebel, Auguste',
 'Brillat-Savarin, Jean Anthelme',
 'Obama, Barack Hussein, II',
 'Pluschow, Gunther',
 'Linnaeus, Carolus',
 'Stoker, Abraham',
 'Lindsay, T. M. (Thomas Martin)',
 'Goose, Mary Susan',
 'Beck, James Montgomery',
 'Stallman, Richard M.',
 'Ubaldino, Petruccio',
 'Borel, Jean',
 'Chevalier, Michael',
 'Glyn, Elinor Sutherland',
 'Lorenc, Frantisek Vladimir',
 'Jacobs, William Wymark',
 'Jagor, Andreas Fedor',
 'Fewkes, J. Walter (Jesse Walter)',
 'Beach, Rex Ellingwood',
 'Crawford, Francis Marion',
 'Boothby, Guy Newell',
 'Ferri, Enrique',
 'Hayes, Charles Frederic',
 'Lonnrot, Elias',
 'Paine, Walter Lionel',
 'Goffic, Charles Le',
 'Brazil. Commissao, Exposicao internacioncal de borracha de New York, 1912',
 'Polko, E. (Elise)',
 'Schopfer, Jean',
 'Oksanen, A.',
 'Junius',
 'Baruch, Moses',
 'Delpit, Marc-Adrien',
 'Ritchie, F. (Francis)',
 'Marcus Vitruvius Pollio',
 'Morley, Christopher Darlington',
 'Roessler, Erwin William Eugene',
 'Philippe, Ch.-L. (Charles-Louis)',
 'Watson, John',
 'Runa',
 'Disraeli, B. (Benjamin), Earl of Beaconsfield',
 'Lasker, Eduard',
 'Coote, Miss',
 'Runeberg, J. L. (Johan Ludvig)',
 'Nansen, P. (Peter)',
 'Blanc, H. (Henry)',
 'Latzko, Adolf Andreas',
 'Newton, Sir Isaac',
 'Voß, Richard',
 'Sinjohn, John',
 'Greenfield, Gulielmus',
 'Collado, D. (Diego)',
 'Keller, Helen Adams',
 'Drago, Luis Maria',
 'Blanche, August Teodor',
 'Slousch, Nahum',
 'Gubernatis, Angelo de, conte',
 'Fry, Sheila Kaye-Smith',
 'Ellis, Henry Havelock',
 'Soderhjelm, Alma',
 '谷崎潤一郎',
 'Wallace, Richard Horatio Edgar',
 'Bushnell, Curtis Clark',
 'Morne, Arvid',
 'Revesz, Bela',
 'Pfeiffer, Ida Reyer',
 'Kyrburg, Fritz von der',
 'Hobson, John Atkinson',
 'Edwardes, Edward Tickner',
 'Donner, O. (Otto)',
 'Maundeville, John',
 'Burckhardt, Jakob Christoph',
 'Alcock, D.',
 'Hocker, Gustav',
 'Mosso, Angelo',
 'Labaigt, Laurent',
 'Aguinaldo y Famy, Emilio',
 'Edwards, O. M., Sir',
 '曹雪芹',
 'Eden, Charles Henry',
 'Tavaststjerna, Karl A. (Karl August)',
 'Bull, Jakob B.',
 'Birt, Theodorus',
 'Rollin, Carol',
 'Friis, Jens Andreas',
 'Gaboriau, Émile',
 'Smith, Sarah',
 'Pennell, Theodore Leighton',
 'Bernard, Paul',
 'Peard, Frances M. (Frances Mary)',
 'Dodge, M. E. (Mary Elizabeth)',
 'Kroeh, Charles F.',
 'Cameron, V. L. (Verney Lovett)',
 'Carlet, Pierre',
 'Roux, Hugues le',
 'Beyrich, Clementine (Helm), Frau',
 'Busch, Julius Hermann Moritz',
 'Endle, S. (Sidney)',
 'Von Liebig, Justus, Freiherr',
 'Gasson, Herbert N. (Herbert Newton)',
 'Maspero, Gaston Camille Charles, Sir',
 'Enochs, James Bryon',
 'Pegge, S. (Samuel)',
 'Aneurin',
 'Caius Julius Phaedrus',
 'Caspari, Karl Heinrich',
 'Corroyer, Édouard',
 'Wecksell, Josef Julius',
 'Gunnarsons, Gunnars',
 'Δημοσθένης',
 'Wedekind, Benjamin Franklin',
 'Guerrazzi, F. D. (Francesco Domenico)',
 'Cairon, Claude Antoine Jules',
 'Blommaert, Willem',
 'Rebecque, Henri Benjamin Constant de',
 'Guthrie, Thomas Anstey',
 'Murray, M. A. (Margaret Alice)',
 'Kloosterman, Jan Ritskes',
 'Mallanaga',
 'Souvestre, Emile',
 'Tourgee, Albion Winegar',
 'Malatesta, Enrico',
 'Robida, A. (Albert)',
 'Anderson, James Drummond',
 'Norris, Benjamin Franklin',
 'Tegner, Esaias',
 'Topelius, Toini Mathilda',
 'Sabatini, R.',
 'Hackluyt, Richard',
 'Holmes, Gordon',
 'Benoit, Pierre',
 'Гончаров, Иван Александрович',
 'Wangemann, Eduard Carl Otto',
 'Kafka, F. (Franz)',
 'Massenet, J. (Jules)',
 'Huch, Ricarda Octavia',
 'Mainwaring, C. L.',
 'Gurdon, Philip Richard Thornhagh',
 'Pearce, Joseph Henry',
 'Pearce, E. H. (Ernest Harold)',
 'Overstreet, Harry Allen',
 'Pain, Thomas',
 'Overseer',
 'Overton, J. H. (John Henry)',
 'Peck, J. M. (John Mason)',
 'Pain, Barry Eric Odell',
 'Peabody, F. W. (Frederick William)',
 'Peabody, E. P. (Elizabeth Palmer)',
 'Pear, Tom Hatherley',
 'Peck, R. H.',
 'Peano, G. (Giuseppe)',
 'Pailleron, Édouard Jules Henri',
 'Overton, Grant Martin',
 'Peake, Harold John Edward',
 'Pace, Thomas C.',
 'Peck, J. L. (John Lord)',
 'Pearce, William P. (William Peter)',
 'Packard, Robert Lewis',
 'Pearson, Arthur Cyril',
 'Packeny, Elsa Maria',
 'Paavo-Kallio, Esaias',
 'Pearson, Charles Henry',
 'Pearse, H. H. S. (Henry Hiram Steere)',
 'P. B. St.',
 'Ozaki, Yukio, Madame',
 'Pearson, E. L. (Edmund Lester)',
 'Oxley, James M. (James Macdonald)',
 'Paddock, Buckley B.',
 'Pearse, Guy Mark',
 'Owen, Robert Latham',
 'Pears, James R.\u200f',
 'Paden, Clifton',
 'Paes, Domingo',
 'Pearson, Thomas Gilbert',
 'Pease, A. E. (Alfred Edward), Sir',
 'Owen, John, Rector of Paglesham, Essex',
 'Paez, Ramon',
 'Paganino, Rodrigo Botelho da Fonseca',
 'Owen, Jean Allan',
 'Pearn, Violet A.',
 'Page, Gerald Wilburn',
 'Paget, Violet',
 'Peck, Annie Smith',
 'Peck, George Wilbur',
 'Payne-Gallwey, Ralph William Frankland, Sir, bart.',
 'Pallander, Gunnar',
 'Payne, Paul Lawrence',
 'Partridge, George Everett',
 'Paris, J. A. (John Ayrton)',
 'Parrish, George Dillwyn',
 'Paredes, Manuel Rigoberto',
 'Parry, Edwin Francis',
 'Pardee, Richard Gay',
 'Parsons, B. (Benjamin)',
 'Parsons, S. B.',
 'Parsons, Wm. Barclay (William Barclay)',
 'Partridge, Edward Bellamy',
 'Paquiro',
 'Payne, Buckner Harrison',
 'Pascal, Theophile',
 'Paske, Charles Thomas',
 'Passos, John Dos',
 'Patanjali',
 'Panton, Jane Ellen',
 'Patch, Edith Marion',
 'Patchin, Frank Glines',
 'Paternoster, George Sidney,',
 'Panshin, Alexis Adams',
 'Park, J. R. (John Ranicar)',
 'Park, James Alan, Sir',
 'Park, Robert E.',
 'Parker, Amos Andrew',
 'Parkman, F. (Francis)',
 'Parker, Louis N. (Louis Napoleon)',
 'Parker, L. S. (Lester Shepard)',
 'Parkman, Mary R.',
 'Parker, James Gordon',
 'Parley, Peter',
 'Parker, J. H. (John Henry)',
 'Parker, Henry',
 'Parker, George, Earl of Macclesfield',
 'Parliament, British',
 'Parloa, Miss (Maria)',
 'Parmanen, Eino I.',
 'Parker, E. H. (Edward Harper)',
 'Parnel, Thomas',
 'Parquet, Marguerite Du',
 'Parker, Dorothy Rothschild',
 'Parker, DeWitt H. (DeWitt Henry)',
 'Parr, Harriet',
 'Parr, Mrs. (Louisa Taylor)',
 'Patmore, Coventry Kersey Dighton',
 'Patmore, Peter George',
 'Paton, Andrew Archibald',
 'Parker, Richard Barry',
 'Palgrave, Francis T.',
 'Patterson, John Henry',
 'Patteson, Susanna Louise',
 'Palffy, Albert',
 'Paul, Ford',
 'Paul, Herbert Woodfield',
 'Paul, Sir John Dean, bart.',
 'Pauli, Simon',
 'Palacios, Pedro Bonifacio',
 'Pakiser, Louis Charles',
 'Pakh, Albert',
 'Paulton, Edward Antonio',
 'Paxson, Frederic Logan',
 'Paxton, John D.',
 'Paivarinta, Pietari',
 'Pay, Committee on Railway Mail',
 'Painter, Franklin Verzelius Newton',
 'Payen, Jean-François',
 'Paine, Ralph D. (Ralph Delahaye)',
 'Patterson, J. M. (Joseph Medill)',
 'Pallme, Ignatius',
 'Panizza, Oscar',
 'Palmer, Alice Elvira Freeman',
 'Panin, I. (Ivan)',
 'Pangloss, docteur',
 'Palmer, William Thomas',
 'Palmer, W. Scott (William Scott)',
 'Paton, John G.',
 'Palmer, Josephine L.',
 'Patrat, J. (Joseph)',
 'Palmer, John Leslie',
 'Palmer, Herbert Edward',
 'Palmer, H. E. (Harold E.)',
 'Patricio, Antonio',
 'Patricio, Ladislau',
 'Patricola',
 'Pattee, George Kynett',
 'Palmer, E. H. (Edward Henry)',
 'Palmer, Donald Ellsworth',
 'Palmer, Austin Norman',
 'Patterson, Anne Virginia Sharpe',
 'Patterson, Caleb Perry',
 'A Bushman',
 'Ohrwalder, Joseph',
 'Ottolini, Vittore',
 'Newark, N.J. College of Engineering',
 'Nicklin, John Arnold',
 'Nicholson, Joseph Shield',
 'Nicholson, James Bartram',
 'Nicholson, H. Alleyne (Henry Alleyne)',
 'Nichols, W. T.',
 'Nichols, Robert Malise Bowyer',
 'Nichols, James Thomas',
 'Nichols, James M.',
 'Nichols, James Lawrence',
 'Nicaise, Charles-Louis Auguste',
 'Newton, R. Heber (Richard Heber)',
 'Newton, John',
 'Newton, Alexander Herritage',
 'Newte, Horace Wykeham Can',
 'Newsholme, Sir Arthur',
 'Newmann, Louis',
 'Newman, F. W. (Francis William)',
 'Newman, Edward Manuel',
 'Newlin, William Henry',
 'Newlin, Katharine',
 'Newland, Henry Garrett',
 'Newell, Robert Henry',
 'Newell, P. S. (Peter S.)',
 'Newell, M. Moyca',
 'Newell, Geo. E.',
 'Newbigin, Marion Isabel',
 'Newberry, Percy Edward',
 'Nicolas, Lady Sarah Davison',
 'Nicolay, John George',
 'Nicolini, Giovanni Battista',
 'Noah, Mordecai Manuel',
 'Nordlund, K. (Karl)',
 'Nordhoff, Charles Bernard',
 'Nordenskiold, A. E. (Adolf Erik)',
 'Nordberg, Carl Edin',
 'Nonagenarian',
 'Noll, R. C.',
 'Nolan, Edward Henry',
 'Nogent, Guibert de',
 'Noe, Sydney Philip',
 'Noe, James Thomas Cotton',
 'Nobre, Antonio',
 'Noble, Theophilus Charles',
 'Nizam-ud-din-Ahmad',
 'Nieboer, Herman Jeremias',
 'Nixon, Oliver Woodson',
 'Niven, Frederick John',
 'Nitsch, Helen Alice Matthews',
 'Nisbet, James Hume',
 'Nilsson, Martin Persson',
 'Nilsen, Eric',
 'Niewadomska, Cecylia',
 'Niemi, A. R. (Aukusti Robert)',
 'Nielsen, Jens Peter Zakarias',
 'Nielsen, Anton',
 'Niederlein, Gustav',
 'Niebuhrius, B. G. (Barthold Georg)',
 'Newberry, Fanny E. (Fanny Ellsworth)',
 'New York detective',
 'Norman, B. M. (Benjamin Moore)',
 'New York Historical Association',
 'Nasmith, George G. (George Gallie)',
 'Nash, Mrs. William H.',
 'Naquet, A. (Alfred)',
 'Napton, W. B. (William Barclay)',
 'Nankivell, Edward James',
 'Name, Addison Van',
 'Nagy, Ignacz',
 'Myers, Philip Van Ness',
 'Myers, Frederic William Henry',
 'Myddleton, William Henry',
 'Muzzey, Artemas Bowers',
 'Mutzenberg, Chas. G.',
 'Mustakallio, Johannes',
 'Musson, S. C. (Spencer C.)',
 'Mussey, Reuben Dimond',
 'Musgrave, Dr. (Samuel)',
 'Musel, Robert',
 'Muse, Ben',
 'Murrey, Thomas Jefferson',
 'Murray, William Henry Harrison',
 'Murray, Thomas Boyles',
 'Murray, Robert Fuller',
 'Murray, James A. H.',
 'Murray, Henry Anthony',
 'Murray, H. Kincaid',
 'Murray, Elsie Riach',
 'Murray, David Leslie',
 'Nassau, R. H. (Robert Hamill)',
 'Nathan, Annie',
 'Nathorst, Alfred Gabriel',
 'Nepomuk',
 'New York (Colony). Legislative Council',
 'Neville, Kris Ottman',
 'Neville, Emily Cheney',
 'Nevill, Ralph Henry',
 'Neveux, Pol Louis',
 'Neuman, Nancy W. Hawkins',
 'Neufeld, Carl',
 'Netscher, A. D. van der gon',
 'Netherton, Ross D. (Ross De Witt)',
 'Nessmuk',
 'Neralc, Jenny',
 'Nepoty, Lucien',
 'Nelson, W. S.',
 'National Live Stock & Meat Board',
 'Nelson, Hector William',
 'Nelson, E. W. (Edward William)',
 'Nelson, Alec',
 'Nelligan, Murray Homer',
 'Nell, William Cooper',
 'Neilson, W. A. (William Allan)',
 'Neill, A. S. (Alexander Sutherland)',
 'Neil, Henry',
 'Neihardt, John Gneisenau',
 'Neef, Frederick Emil',
 'Nearing, Alice Eleanor',
 'Naylor, James Ball',
 'Nordstrom, Ester Blenda',
 'Norman, C. B.',
 'Otto, Karl Ludwig Rudolf',
 'Odonais, Jean Godin des',
 'Omond, G. W. T. (George William Thomson)',
 'Olufs, Harck',
 'Olsen, Alfred Johannes, Jr.',
 'Olmstead, Frederick Law',
 'Olmstead, Denison',
 'Olmstead, Charles Hart',
 'Olmstead, Albert Ten Eyck',
 'Ollefen, L. V. (Lieve van)',
 'Oliver, Joseph Tombs',
 'Oliver, George',
 'Oliphant, S. Grant',
 'Oliphant, Lawrence',
 'Olin, Julia Matilda Lynch',
 'Olin, George Joyce',
 'Oldys, Francis',
 'Oldington, Richard',
 'Old Fogy',
 'Olcott, H. S. (Henry Steel)',
 'Olcott, Charles Sumner',
 'Olah, Gabor',
 'Okenfuss, Lorenz',
 'Oinophilus, Boniface',
 'Peckham, Elizabeth Gifford',
 'Ogden, H. N. (Henry Neely)',
 'Ogden Stewart, Donald',
 'Officer, A British',
 'Office, White Sands Missile Range Public Affairs',
 'Openhaimer, Frants',
 'Oppenheim, Lassa Francis Lawrence',
 'Oppenheim, Max von',
 'Orton, J. W. (James W.)',
 'Otto, Ernst von',
 'Otis, C. H.',
 'Ostwald, Hans Otto August',
 'Ostrander, Stephen',
 'Ostergaard, Vilhelm',
 'Osmun, Thomas Embley',
 'Osmer, W. (William)',
 'Osler, Sir William',
 'Oskison, Hildegarde Hawthorne',
 'Osborne, Richardson',
 'Osborn, Henry Stafford',
 'Osborn, Henry F. (Henry Fairfield)',
 'Orr, Charles E.',
 'Oppenheim, Michael Morris',
 'Orr, Anne Champe',
 'Orndorff, Frank Milliken',
 'Ormsbee, Thomas Hamilton',
 'Ormerod, E. A. (Eleanor Anne)',
 'Ordway, Edith Bertha',
 'Ordonneau, M. (Maurice)',
 'Orcutt, Wm. Dana (William Dana)',
 'Orchestra, Broadway Dance',
 'Orchard, William Edwin',
 'Orban, Balazs',
 'Orage, Alfred Richard',
 'Or-Ot',
 'Odum, Howard W.',
 'Odle, Edwin Vincent',
 'Norman, Wm. B.',
 'Odell, Ernest Gregory',
 'Nyiro, Jozsef',
 'Nycander, Fredrik Axel\u200f',
 'Nyblom, Helena Augusta (Roed)',
 'Nutt, Alfred Trubner',
 'Nurmio, Heikki',
 'Nurmi, Bruno Bernhard',
 'Nunes, Robert',
 'Nunes, Claudio Jose',
 'Nugent, Homer H. (Homer Heath)',
 'Noyes, Margaret Ella',
 'Noyes, J. H. (John Humphrey)',
 'Noyes, Henry Edward',
 'Noyes, Ethel Jane Russell Chesebrough',
 'Novak, Jan Vaclav',
 'Nott, Charles Cooper',
 'Nostradamus, Merlin',
 'Norwood, Robert W.',
 'Norway, George',
 'Norton, M. M. (Morilla Maria)',
 'Norton, Arthur Orlo',
 'Northington, Etta Belle Walker',
 'Northend, Mary H.',
 'Northcote, James Spencer',
 'Norris, Zoe Anderson',
 'Norris, H. L.',
 'Normann, Friedrich Gustav',
 'Normand, Jacques Clary Jean',
 'Nyman, Severi',
 'Nyrop, Christopher',
 'Nyswander, Marie',
 "O'Kelly, Seamus",
 'Ockside, Russ, Knight',
 'Ocantos, Carlos Maria',
 'Oberfield, Bill',
 'Ober, C. K. (Charles Kellogg)',
 'Obdrzalek, Peregrin',
 "O'Shaugnessy, Arthur",
 "O'Shaughnessy, William Brooke",
 "O'Reilly, Augustine J.",
 "O'Pagus, Arry",
 "O'Neale, Lila Morris",
 "O'Meara, J. (James)",
 "O'Mahony, Charles K.",
 "O'Keefe, John",
 "O'Brien, C.",
 "O'Higgins, Harvey J.",
 "O'Hegarty, Patrick Sarsfield",
 "O'Hara, Kenneth",
 "O'Donnell, Elliot",
 "O'Doherty, Morgan, Sir",
 "O'Cotter, Pat",
 "O'Connor, Thomas Power",
 "O'Connor, John L. (John Lawrence)",
 "O'Connor, Edward",
 "O'Brien, George Augustine Thomas",
 "O'Brien, Frank M. (Frank Michael)",
 "O'Brien, Francis Paul",
 'Peck, Robert M.',
 'Picken, Mary Brooks',
 'Peckham, G. W. (George Williams)',
 'Randal, Florence Hamilton',
 'Ray, George Raymond (Holman)',
 'Ray, G. Whitfield (George Whitfield)',
 'Ray, Fan',
 'Rawnsley, Willingham Franklin',
 'Rawnsley, Hardwicke Drummond',
 'Rawlinson, William George',
 'Rawlings, G. B. (Gertrude Burford)',
 'Rawling, L. Bathe (Louis Bathe)',
 'Ravnkilde, Adele Marie',
 'Rausch, Albert Heinrich',
 'Rauhala, Kalle Nikodemus',
 'Rauanheimo, Yrjo',
 'Rathbone, W. (William)',
 'Rasmussen, Knud Johan Victor',
 'Rasières, Isaack de',
 'Rasila, Heikki',
 'Rasanen, Ilmari',
 'Rarey, John Solomon',
 'Raphael, John Nathan Percival',
 'Ransom, R. C.',
 'Ransom, Olive',
 'Ransom, B. H. (Brayton Howard)',
 'Ranney, David James',
 'Rankin, Richard C.',
 'Ranger, Seth',
 'Ranger, Charles',
 'Randolph, Sarah Nicholas',
 'Randolph, Beverly S.',
 'Randolph, Berkeley William',
 'Ray, James Ralph',
 'Raymond, Evelyn Hunt',
 'Raymond, George L. (George Lansing)',
 'Redgrove, Herbert Stanley',
 'Reeve, Arthur Benjamin',
 'Rees, Alfred W.',
 'Reeks, Harry Caulton',
 'Reed, Samuel Burrage',
 'Reed, Louise',
 'Reed, Louis C. M.',
 'Reed, Frederick Richard Cowper',
 'Reed, Earl Howell',
 'Reed, E. T. (Edward Tennyson)',
 'Reed, Chester Albert',
 'Reed, Charles Bert',
 'Redway (Firm)',
 'Redondo, Manuel Ferreira Garcia',
 'Reddaway, W. F. (William Fiddian)',
 'Raymond, Rossiter Worthington',